spring:
  datasource:
    username: doston
    password: doston123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/invoice_task
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs